version: '3.9'

services:

  db:
    image: postgres:15
    container_name: pdv_postgres
    restart: always
    environment:
      POSTGRES_DB: pdv_market_coffee
      POSTGRES_USER: usuario_do_banco_de_dados
      POSTGRES_PASSWORD: senha_do_banco_de_dados
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: pdv_backend
    restart: always
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: pdv_market_coffee
      DB_USER: usuario_do_banco_de_dados
      DB_PASSWORD: senha_do_banco_de_dados
      SECRET_KEY: uma_chave_secreta_qualquer
      FLASK_ENV: production
    ports:
      - "8000:8000"
    depends_on:
      - db

frontend:
    build: ./frontend
    container_name: pdv_frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  db_data:

